#! python3
"""
Just some stuff to test with the automate the boring stuff site
"""
import re
import pyperclip
from urllib.request import urlopen, Request

req = Request("https://www.nostarch.com/contactus.htm", headers={"User-Agent": "Mozilla/5.0"})
url = urlopen(req).read()
# print(url)

phone_regex = re.compile(r'''(
(\d{3}|\(\d{3}\))?              # area code
(\s|-|\.)?                      # separator
(\d{3})                         # first 3 digits
(\s|-|\.)                       # separator 
(\d{4})                         # last 4 digits
(\s*(ext|x|ext.)\s*(\d{2,5}))?  # extension
)''', re.VERBOSE)

# Create email regex
email_regex = re.compile(r'''(
[a-zA-Z0-9._%+-]+  # username
@                  # @ symbol
[a-zA-Z0-9.-]+     # domain name
(\.[a-zA-Z]{2,4})  # dot-something, i.e. .com, .net
)''', re.VERBOSE)


# Find all matches in clipboard text
# text = str(pyperclip.paste())
text = str(url)
matches = []

for groups in phone_regex.findall(text):
    phone_number = "-".join([groups[1], groups[3], groups[5]])

    if groups[8] != "":
        phone_number += " x" + groups[8]
    matches.append(phone_number)

for groups in email_regex.findall(text):
    matches.append(groups[0])

# Copy results to the clipboard
if len(matches) > 0:
    pyperclip.copy("\n".join(matches))
    print("Copied to clipboard:")
    print("\n".join(matches))
else:
    print("No phone numbers or email addresses found.")
